SELECT * FROM CIDADES WHERE CIDADES.NOME LIKE 'PORTO%' 
AND CIDADES.POPULACAO_2010 > 20000

SELECT * FROM CIDADES

SELECT SUM(CIDADES.POPULACAO_2010) [POPULACAO], ESTADOS.NOME FROM CIDADES
INNER JOIN ESTADOS ON ESTADOS.ID = CIDADES.ESTADO_ID
GROUP BY ESTADOS.NOME
HAVING SUM (CIDADES.POPULACAO_2010) > 10000000
ORDER BY POPULACAO