create database FARMACIA

USE FARMACIA

CREATE TABLE FABRICANTE
(
	CODIGO_FABRICANTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40) UNIQUE NOT NULL,
	CNPJ VARCHAR(50) NOT NULL
)

CREATE TABLE REMEDIO
(
	CODIGO_REMEDIO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(60) NOT NULL,
	DATAVALIDADE DATETIME NOT NULL,
	CODIGO_FABRICANTE INT
)

ALTER TABLE REMEDIO ADD CONSTRAINT REGRA_REMEDIO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE (CODIGO_FABRICANTE)


INSERT FABRICANTE
(
	NOME,
	CNPJ
)
VALUES
(
	'ASTRA ZENECA',
	'87.132.456/0001-21'
)

INSERT REMEDIO
(
	NOME,
	DATAVALIDADE,
	CODIGO_FABRICANTE
)
VALUES
(
	'CIMEGRIPE',
	'22/02/2025',
	1
)


SELECT * FROM REMEDIO


SELECT REMEDIO.CODIGO_REMEDIO, REMEDIO.NOME, REMEDIO.DATAVALIDADE, FABRICANTE.NOME, FABRICANTE.CNPJ  from REMEDIO 
inner join FABRICANTE on FABRICANTE.CODIGO_FABRICANTE = REMEDIO.CODIGO_FABRICANTE WHERE FABRICANTE.NOME = 'MODERNA' AND REMEDIO.NOME LIKE '%PAM'

--Faça uma consulta que traga o nome do paciente, a datadenascimento, remédio, receitada, datadaconsulta, médico que atendeu, crm, especialidade e a doença
--de todos os pacientes que tenham 'c' nome e a especialidade seja ortopedia, ordene pelo nome do paciente.

Select PACIENTE.NOME, PACIENTE.DATANASC, PRESCRICAO.DESCRICAO_PRESCRICAO, ATENDIMENTO.DATAHORA, MEDICO.NOME, MEDICO.CRM, ESPECIALIDADE.NOME, DOENCA.NOME from MEDICO
inner join DOENCA on CODIGO_DOENCA = CODIGO_MEDICO
inner join ESPECIALIDADE on ESPECIALIDADE.CODIGO_ESPECIALIDADE = MEDICO.CODIGO_MEDICO 
inner join PACIENTE on PACIENTE.CODIGO_PACIENTE = MEDICO.CODIGO_MEDICO
inner join PRESCRICAO on CODIGO_PRESCRICAO = MEDICO.CODIGO_MEDICO
inner join ATENDIMENTO on ATENDIMENTO.CODIGO_ATENDIMENTO = ATENDIMENTO.CODIGO_ATENDIMENTO
where ESPECIALIDADE.NOME = 'ORTOPEDIA' AND PACIENTE.NOME LIKE '%C%' 

--CODIGO PROFESSOR --
Select  ATT.DATAHORA [DATA ATENDIMENTO], ATT.DESCRICAO [DESC ATENDIMENTO], PAC.NOME [PACIENTE], PAC.CPF, PAC.DATANASC, PRES.DESCRICAO_PRESCRICAO [DESCRICAO], 
		MED.NOME [MEDICO], MED.CRM [CRM], DOE.NOME [DOENCA]
	FROM ATENDIMENTO ATT
		INNER JOIN PACIENTE PAC ON PAC.CODIGO_PACIENTE = ATT.CODIGO_PACIENTE
		INNER JOIN PRESCRICAO PRES ON PRES.CODIGO_PRESCRICAO = ATT.CODIGO_PACIENTE
		INNER JOIN MEDICO MED ON MED.CODIGO_MEDICO = ATT.CODIGO_MEDICO
		INNER JOIN DOENCA DOE ON DOE.CODIGO_DOENCA = ATT.CODIGO_ATENDIMENTO
		INNER JOIN ESPECIALIDADE ESP ON ESP.CODIGO_ESPECIALIDADE = MED.CODIGO_ESPECIALIDADE
	WHERE ESP.NOME = 'ORTOPEDIA' OR PAC.NOME LIKE '%C%'
		ORDER BY PAC.NOME

-- Qual o paciente que foi atendido pela ultima vez, quando foi, qual medico atendeu e qual remedio foi receitado.

Select PACIENTE.NOME, ATENDIMENTO.DATAHORA, MEDICO.NOME, PRESCRICAO.DESCRICAO_PRESCRICAO from MEDICO
inner join PRESCRICAO on CODIGO_PRESCRICAO = MEDICO.CODIGO_MEDICO
inner join PACIENTE on PACIENTE.CODIGO_PACIENTE = MEDICO.CODIGO_MEDICO
inner join ATENDIMENTO on ATENDIMENTO.CODIGO_ATENDIMENTO = ATENDIMENTO.CODIGO_ATENDIMENTO
order by ATENDIMENTO.DATAHORA

--CODIGO PROFESSOR
Select TOP 1 ATT.DATAHORA [DATA ATENDIMENTO], ATT.DESCRICAO [DESC ATENDIMENTO], PAC.NOME [PACIENTE], PAC.CPF, PAC.DATANASC, PRES.DESCRICAO_PRESCRICAO [DESCRICAO], 
		MED.NOME [MEDICO], MED.CRM [CRM], DOE.NOME [DOENCA]
	FROM ATENDIMENTO ATT
		INNER JOIN PACIENTE PAC ON PAC.CODIGO_PACIENTE = ATT.CODIGO_PACIENTE
		INNER JOIN PRESCRICAO PRES ON PRES.CODIGO_PRESCRICAO = ATT.CODIGO_PACIENTE
		INNER JOIN MEDICO MED ON MED.CODIGO_MEDICO = ATT.CODIGO_MEDICO
		INNER JOIN DOENCA DOE ON DOE.CODIGO_DOENCA = ATT.CODIGO_ATENDIMENTO
		INNER JOIN ESPECIALIDADE ESP ON ESP.CODIGO_ESPECIALIDADE = MED.CODIGO_ESPECIALIDADE
		ORDER BY ATT.DATAHORA DESC
		