create database ESTOQUE

USE ESTOQUE

CREATE TABLE PESSOA
(
	CODIGO_PESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	DATANASCIMENTO DATETIME
)

CREATE TABLE PRODUTO
(
	CODIGO_PRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_DECIMAL DECIMAL(7,2) NOT NULL
)

CREATE TABLE VENDA
(
	CODIGO_VENDA INT PRIMARY KEY IDENTITY,
	--CODIGO_PESSOA INT,
	DATA_COMPRA DATETIME NOT NULL,
	VALOR_VENDA DECIMAL(10,2)
)

CREATE TABLE ITEM_VENDA
(
	CODIGO_ITEM_VENDA INT PRIMARY KEY IDENTITY,
	--CODIGO_PRODUTO INT FK,
	QUANTIDADE INT NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	--CODIGO_VENDA INT FK
)

ALTER TABLE VENDA ADD CODIGO_PESSOA INT --ALTERAR UMA TABELA E ACRESCENTAR UMA COLUNA
ALTER TABLE ITEM_VENDA ADD CODIGO_PRODUTO INT
ALTER TABLE ITEM_VENDA ADD CODIGO_VENDA INT

ALTER TABLE VENDA --RECEBE A CHAVE FK
ADD CONSTRAINT REGRA_PESSOA FOREIGN KEY --CRIAR CHAVE ESTRANGEIRA
(CODIGO_PESSOA)-- TRANFORMA A TABELA EM FK
REFERENCES PESSOA (CODIGO_PESSOA) -- ONDE VAI PEGAR A CHAVE PRIMARIA DA OUTRA TABELA

ALTER TABLE ITEM_VENDA ADD CONSTRAINT REGRA_ITEM_VENDA FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)
ALTER TABLE ITEM_VENDA ADD CONSTRAINT REGRA_COD_VENDA FOREIGN KEY (CODIGO_VENDA) REFERENCES VENDA (CODIGO_VENDA)

UPDATE PESSOA SET NOME = 'FIAT' WHERE CODIGO_PESSOA = 4 --ALTERA NOME DE TODOS AS COLUNAS 'FIAT' 
DELETE FROM PESSOA WHERE CODIGO_PESSOA = 4 -- DELETA CODIGO 4 DA COLUNA CODIGO_PESSOA

INSERT PESSOA
(
	NOME,
	CPF,
	DATANASCIMENTO

)
VALUES
(
	'MARCELA CAROLINA',
	'332,428,112,96',
	'14/06/2000'
)

INSERT PRODUTO
(
	NOME,
	QUANTIDADE,
	VALOR_DECIMAL
)
VALUES
(
	'FEIJOADA',
	'3',
	'79.99'
)

INSERT VENDA
(
	CODIGO_PESSOA,
	DATA_COMPRA,
	VALOR_VENDA
)
VALUES
(
	'2',
	'22/12/2022',
	'300.00'
	
)

INSERT ITEM_VENDA
(
	CODIGO_PRODUTO,
	QUANTIDADE,
	VALOR,
	CODIGO_VENDA
)
VALUES
(
	2,
	2,
	10.00,
	2
)

SELECT * FROM ITEM_VENDA