create database QUEST

USE QUEST

CREATE TABLE PESSOA
(
	CODIGO_PESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40) UNIQUE NOT NULL,
	ENDERECO VARCHAR(70)
)

CREATE TABLE PESFISICA
(
	CODIGO_PESFISICA INT PRIMARY KEY IDENTITY,
	CPF VARCHAR(60) NOT NULL,
	DATANASC DATETIME NOT NULL,
	--CODIGO_PESSOA INT
)

CREATE TABLE PESJURIDICA
(
	CODIGO_PESJURIDICA INT PRIMARY KEY IDENTITY,
	NOME_FANTASIA VARCHAR(50) NOT NULL,
	CNPJ VARCHAR(18) UNIQUE,
	--CODIGO_PESSOA INT
)

ALTER TABLE PESFISICA ADD CONSTRAINT REGRA_PESFISICA FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA (CODIGO_PESSOA)
ALTER TABLE PESJURIDICA ADD CONSTRAINT REGRA_PESJURIDICA FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA (CODIGO_PESSOA)


INSERT PESSOA
(
	NOME,
	ENDERECO
)
VALUES
(
	'ERIK MARTINS',
	'BELA VISTA'
)

INSERT PESFISICA
(
	CPF,
	DATANASC,
	CODIGO_PESSOA
)
VALUES
(
	'254.456.789.10',
	'31/12/1992',
	1
)

INSERT PESJURIDICA
(
	NOME_FANTASIA,
	CNPJ,
	CODIGO_PESSOA
)
VALUES
(
	'PAINEIS DESING',
	'70.447.175.0001/10',
	3
)



SELECT * FROM PESSOA
SELECT * FROM PESFISICA
SELECT * FROM PESJURIDICA

SELECT PESSOA.CODIGO_PESSOA, PESSOA.NOME, PESSOA.ENDERECO, PESFISICA.CPF, PESFISICA.DATANASC, PESJURIDICA.CNPJ, PESJURIDICA.NOME_FANTASIA from PESSOA 
inner join PESFISICA on PESFISICA.CODIGO_PESSOA = PESSOA.CODIGO_PESSOA
inner join PESJURIDICA on PESJURIDICA.CODIGO_PESSOA = PESSOA.CODIGO_PESSOA
WHERE PESSOA.NOME = 'CELIO TINTI' AND PESSOA.ENDERECO LIKE '%GAS'
