create database CLINICA

USE CLINICA
CREATE TABLE MEDICO
(
	CODIGO_MEDICO INT PRIMARY KEY IDENTITY,
	CRM VARCHAR(12) UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	--CODIGO_ESPECIALIDADE INT FK,
)

CREATE TABLE ESPECIALIDADE
(
	CODIGO_ESPECIALIDADE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
)

CREATE TABLE ATENDIMENTO
(
	CODIGO_ATENDIMENTO INT PRIMARY KEY IDENTITY,
	DATAHORA DATETIME NOT NULL,
	--CODIGO_PACIENTE INT , FK
	--CODIGO_MEDICO INT , FK
	--CODIGO_DOENCA INT , FK
	DESCRICAO VARCHAR(2000) NOT NULL,  
)

CREATE TABLE DOENCA
(
	CODIGO_DOENCA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40) NOT NULL,
	CID VARCHAR(10) NOT NULL,
)

CREATE TABLE PACIENTE
(
	CODIGO_PACIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(40) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	PESO DECIMAL(5,2) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATANASC DATETIME NOT NULL,
)

CREATE TABLE PRESCRICAO
(
	CODIGO_PRESCRICAO INT PRIMARY KEY IDENTITY,
	DESCRICAO_PRESCRICAO VARCHAR(200) NOT NULL,
	--CODIGO_ATENDIMENTO INT, FK
)


ALTER TABLE MEDICO ADD CONSTRAINT REGRA_MEDICO FOREIGN KEY (CODIGO_ESPECIALIDADE) REFERENCES ESPECIALIDADE (CODIGO_ESPECIALIDADE)
ALTER TABLE ATENDIMENTO ADD CONSTRAINT REGRA_ATENDIMENTO FOREIGN KEY (CODIGO_PACIENTE) REFERENCES PACIENTE (CODIGO_PACIENTE)
ALTER TABLE ATENDIMENTO ADD CONSTRAINT REGRA_ATENDIMENTO2 FOREIGN KEY (CODIGO_MEDICO) REFERENCES MEDICO (CODIGO_MEDICO)
ALTER TABLE ATENDIMENTO ADD CONSTRAINT REGRA_ATENDIMENTO3 FOREIGN KEY (CODIGO_DOENCA) REFERENCES DOENCA (CODIGO_DOENCA)
ALTER TABLE PRESCRICAO ADD CONSTRAINT REGRA_ATENDIMENTO4 FOREIGN KEY (CODIGO_ATENDIMENTO) REFERENCES ATENDIMENTO (CODIGO_ATENDIMENTO)

INSERT MEDICO
(
	CRM,
	NOME
)
VALUES
(
	'CRMRJ 853369',
	'ANA PAULA'
)

INSERT ESPECIALIDADE
(
	NOME
)
VALUES
(
	'ORTOPEDIA '
)

INSERT PACIENTE
(
	NOME,
	CPF,
	PESO,
	SEXO

)
VALUES
(
	'Colesterol',
	'G93_8'
)


SELECT * FROM MEDICO

like '%ra' -- tudo antes do 'r' vai aparecer 'ra' final da palavra.
and --tem que ser verdadeiro todas as condições,
or -- uma ou outra tem que ser verdadeiro
order by  -- ordenar pela coluna que for colocada
order by asc -- ordem alfabetica -- desc do menor para maior (asc não precisa colocar já fica automatico)

SELECT MEDICO.NOME, MEDICO.CODIGO_MEDICO, MEDICO.CRM from MEDICO where nome like '%A' --where indica qual coluna sera feita a consulta.

SELECT MEDICO.NOME, MEDICO.CRM, ESPECIALIDADE.NOME from MEDICO 
inner join ESPECIALIDADE on ESPECIALIDADE.CODIGO_ESPECIALIDADE = MEDICO.CODIGO_MEDICO where ESPECIALIDADE.NOME = 'PEDIATRA' -- AND MEDICO.NOME like '%A' DEU PROBLEMA

UPDATE MEDICO SET CODIGO_ESPECIALIDADE = 4 WHERE CODIGO_MEDICO = '12';

--Faça uma consulta que traga o nome do paciente, a datadenascimento, remédio, receitada, datadaconsulta, médico que atendeu, crm, especialidade e a doença
--de todos os pacientes que tenham 'c' nome e a especialidade seja ortopedia, ordene pelo nome do paciente.

Select PACIENTE.NOME, PACIENTE.DATANASC, PRESCRICAO.DESCRICAO_PRESCRICAO, ATENDIMENTO.DATAHORA, MEDICO.NOME, MEDICO.CRM, ESPECIALIDADE.NOME, DOENCA.NOME from MEDICO
inner join DOENCA on CODIGO_DOENCA = CODIGO_MEDICO
inner join ESPECIALIDADE on ESPECIALIDADE.CODIGO_ESPECIALIDADE = MEDICO.CODIGO_MEDICO 
inner join PACIENTE on PACIENTE.CODIGO_PACIENTE = MEDICO.CODIGO_MEDICO
inner join PRESCRICAO on CODIGO_PRESCRICAO = MEDICO.CODIGO_MEDICO
inner join ATENDIMENTO on ATENDIMENTO.CODIGO_ATENDIMENTO = ATENDIMENTO.CODIGO_ATENDIMENTO
where ESPECIALIDADE.NOME = 'ORTOPEDIA' AND PACIENTE.NOME LIKE '%C%' 

--CODIGO PROFESSOR --
Select  ATT.DATAHORA [DATA ATENDIMENTO], ATT.DESCRICAO [DESC ATENDIMENTO], PAC.NOME [PACIENTE], PAC.CPF, PAC.DATANASC, PRES.DESCRICAO_PRESCRICAO [DESCRICAO], 
		MED.NOME [MEDICO], MED.CRM [CRM], DOE.NOME [DOENCA]
	FROM ATENDIMENTO ATT
		INNER JOIN PACIENTE PAC ON PAC.CODIGO_PACIENTE = ATT.CODIGO_PACIENTE
		INNER JOIN PRESCRICAO PRES ON PRES.CODIGO_PRESCRICAO = ATT.CODIGO_PACIENTE
		INNER JOIN MEDICO MED ON MED.CODIGO_MEDICO = ATT.CODIGO_MEDICO
		INNER JOIN DOENCA DOE ON DOE.CODIGO_DOENCA = ATT.CODIGO_ATENDIMENTO
		INNER JOIN ESPECIALIDADE ESP ON ESP.CODIGO_ESPECIALIDADE = MED.CODIGO_ESPECIALIDADE
	WHERE ESP.NOME = 'ORTOPEDIA' OR PAC.NOME LIKE '%C%'
		ORDER BY PAC.NOME

-- Qual o paciente que foi atendido pela ultima vez, quando foi, qual medico atendeu e qual remedio foi receitado.

Select PACIENTE.NOME, ATENDIMENTO.DATAHORA, MEDICO.NOME, PRESCRICAO.DESCRICAO_PRESCRICAO from MEDICO
inner join PRESCRICAO on CODIGO_PRESCRICAO = MEDICO.CODIGO_MEDICO
inner join PACIENTE on PACIENTE.CODIGO_PACIENTE = MEDICO.CODIGO_MEDICO
inner join ATENDIMENTO on ATENDIMENTO.CODIGO_ATENDIMENTO = ATENDIMENTO.CODIGO_ATENDIMENTO
order by ATENDIMENTO.DATAHORA

--CODIGO PROFESSOR
Select TOP 1 ATT.DATAHORA [DATA ATENDIMENTO], ATT.DESCRICAO [DESC ATENDIMENTO], PAC.NOME [PACIENTE], PAC.CPF, PAC.DATANASC, PRES.DESCRICAO_PRESCRICAO [DESCRICAO], 
		MED.NOME [MEDICO], MED.CRM [CRM], DOE.NOME [DOENCA]
	FROM ATENDIMENTO ATT
		INNER JOIN PACIENTE PAC ON PAC.CODIGO_PACIENTE = ATT.CODIGO_PACIENTE
		INNER JOIN PRESCRICAO PRES ON PRES.CODIGO_PRESCRICAO = ATT.CODIGO_PACIENTE
		INNER JOIN MEDICO MED ON MED.CODIGO_MEDICO = ATT.CODIGO_MEDICO
		INNER JOIN DOENCA DOE ON DOE.CODIGO_DOENCA = ATT.CODIGO_ATENDIMENTO
		INNER JOIN ESPECIALIDADE ESP ON ESP.CODIGO_ESPECIALIDADE = MED.CODIGO_ESPECIALIDADE
		ORDER BY ATT.DATAHORA DESC
		