create database LOJACARRO

USE LOJACARRO

CREATE TABLE MODELO
(
	CODIGO INT PRIMARY KEY IDENTITY,
	NOMECARRO VARCHAR(40) NOT NULL,
	COR VARCHAR(30) NOT NULL,
	PLACA VARCHAR(7) UNIQUE
)

ALTER TABLE MODELO ADD CODIGOMARCA INT

ALTER TABLE MODELO ADD CONSTRAINT MARCAMODELO FOREIGN KEY
(CODIGOMARCA) REFERENCES MARCA (CODIGOMARCA)

CREATE TABLE MARCA
(
	CODIGOMARCA INT PRIMARY KEY IDENTITY,
	NOMEMARCA VARCHAR(40)
)

INSERT MARCA
(
	NOMEMARCA
)
VALUES
(
	'FIAT'
)

SELECT * FROM MARCA